# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c5409a23595c79207efa162434a71e1709123cd02357ff1360ed6bc34d3636c14d9aab8f6d27290a0169460299646874e5e0cc4f7d3d5d539957ff4f03c4254

test:
  secret_key_base: 5f94a793a2ef1a4cbba5eb391312c23588a9ce3b560e2957b0ff3f4992040dca6ef792cb244b777db0ad6ebd855498a7018accab9b5578019bcb384d2a86d30b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
